### ISSUE TITLE
possible bug and getopts

### ISSUE THREAD

**Issue by hkmaverick** [extremeshok/clamav-unofficial-sigs#113] opened 2016-05-12 03:18 UTC
in script version 5.3.0 line 1854:
if ! $gpg_bin --trust-model always -q --no-default-keyring.......
exit code 0 equals true in bash, so shouldn't the ! be removed? so subsequent gpg signature tests could be run.

found instances of $OPTARG in the script but getopts was never called.

**Comment by DamianoBianchi** [comment] 2016-05-13 12:18
It seems correct to me, the problem is that the ret variable seems not to be evaluated correctly. I just opened a new issue on such topic.

**Comment by extremeshok** [comment] 2016-05-13 17:30
gpg issue fixed in 232f4fcea8474f62ad3ec0e83cf62fd6cf65a3c7

**Comment by extremeshok** [comment] 2016-05-13 18:01
getops fixed with 885147e1cecc2d03b45b25152ef2b42b443f4cb0

**Comment by extremeshok** [comment] 2016-05-13 18:02
thank you

**Closed by extremeshok** 2016-05-13 18:02 UTC
