### ISSUE TITLE
Hourly emails /usr/local/sbin/clamav-unofficial-sigs.sh: Line 1808: alwaredetect_dir: Command not found 

### ISSUE THREAD

**Issue by 3por2** [extremeshok/clamav-unofficial-sigs#282] opened 2020-01-24 13:13 UTC
After yesterday's update I get the following error message every hour during the database check:

`/usr/local/sbin/clamav-unofficial-sigs.sh: Line 1808: alwaredetect_dir: Command not found`

I have checked the file, but I cannot find such an entry. 

System: Ubuntu 16.04

**Comment by extremeshok** [comment] 2020-01-24 13:48
duplicate of #281 
fixed in dev

**Closed by extremeshok** 2020-01-24 13:48 UTC
